# Data Analysis — NumPy & Pandas

**Topics covered:**
1. NumPy arrays
2. Broadcasting
3. Pandas DataFrame
4. Reading CSV / Excel / JSON
5. Filtering
6. GroupBy
7. Missing value handling
8. Data preprocessing
9. Feature engineering basics

Work through each section top to bottom. Type the code yourself instead of just running it — that's how it sticks. Each section ends with 1-2 practice questions; try them before moving on.

In [1]:
# Run this first to install/check the libraries we need
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.4.4
Pandas version: 3.0.2

## 1. NumPy Arrays

A NumPy array (`ndarray`) is like a Python list, but faster and built for math. All elements
must be the same data type (e.g. all integers, or all floats).

In [2]:
# Creating arrays
a1 = np.array([1, 2, 3, 4, 5])              # 1-D array
a2 = np.array([[1, 2, 3], [4, 5, 6]])       # 2-D array (matrix)

print("a1:", a1)
print("a2:\n", a2)
print("Shape of a1:", a1.shape)
print("Shape of a2:", a2.shape)
print("Data type:", a1.dtype)

a1: [1 2 3 4 5]
a2:
 [[1 2 3]
 [4 5 6]]
Shape of a1: (5,)
Shape of a2: (2, 3)
Data type: int64

In [3]:
# Common ways to create arrays without typing every value
zeros = np.zeros((2, 3))        # 2x3 array of zeros
ones = np.ones((3, 3))          # 3x3 array of ones
rng = np.arange(0, 10, 2)       # start, stop, step -> [0 2 4 6 8]
lin = np.linspace(0, 1, 5)      # 5 evenly spaced numbers from 0 to 1

print("zeros:\n", zeros)
print("ones:\n", ones)
print("arange:", rng)
print("linspace:", lin)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]

In [4]:
# Indexing and slicing (very similar to Python lists)
a = np.array([10, 20, 30, 40, 50])

print("First element:", a[0])
print("Last element:", a[-1])
print("Slice [1:4]:", a[1:4])

# 2-D indexing: [row, column]
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at row 1, col 2:", b[1, 2])   # 6
print("Whole second row:", b[1, :])
print("Whole third column:", b[:, 2])

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Element at row 1, col 2: 6
Whole second row: [4 5 6]
Whole third column: [3 6 9]

In [5]:
# Array attributes and basic operations
a = np.array([[1, 2, 3], [4, 5, 6]])

print("ndim (dimensions):", a.ndim)
print("size (total elements):", a.size)
print("dtype:", a.dtype)

# Element-wise math (NOT like Python list math!)
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
print("x + y:", x + y)
print("x * y:", x * y)
print("x ** 2:", x ** 2)

# Useful aggregate functions
print("sum:", x.sum())
print("mean:", x.mean())
print("max:", x.max(), " min:", x.min())
print("std (standard deviation):", x.std())

ndim (dimensions): 2
size (total elements): 6
dtype: int64
x + y: [11 22 33]
x * y: [10 40 90]
x ** 2: [1 4 9]
sum: 6
mean: 2.0
max: 3  min: 1
std (standard deviation): 0.816496580927726

**Practice 1**
1. Create a 1-D NumPy array of the numbers 1 to 10 using `np.arange`.
2. Reshape it into a 2x5 array using `.reshape(2, 5)`.
3. Print the mean of each row using `array.mean(axis=1)`.

In [6]:
# Your practice code here

## 2. Broadcasting

Broadcasting is NumPy's way of letting arrays of **different shapes** work together in
arithmetic operations, without you writing a loop. NumPy automatically "stretches" the
smaller array to match the bigger one, as long as the shapes are compatible.

**Rule of thumb:** compare shapes from right to left. Two dimensions are compatible if
they are equal, or one of them is 1.

In [7]:
# Example 1: scalar + array (simplest form of broadcasting)
a = np.array([1, 2, 3])
print(a + 10)   # 10 is "broadcast" to [10, 10, 10]

[11 12 13]

In [8]:
# Example 2: 1-D array + 2-D array
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
row = np.array([10, 20, 30])   # shape (3,)

# row is broadcast across every row of matrix
print(matrix + row)

[[11 22 33]
 [14 25 36]
 [17 28 39]]

In [9]:
# Example 3: column vector + row vector -> produces a full grid
col = np.array([[0], [10], [20]])   # shape (3, 1)
row = np.array([1, 2, 3])           # shape (3,)

print(col + row)
# Result is a (3,3) matrix: each row of col added to the whole row vector

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]

In [10]:
# Example 4: broadcasting failure (shapes incompatible)
try:
    bad = np.array([1, 2, 3]) + np.array([1, 2])
except ValueError as e:
    print("Error:", e)
# 3 vs 2 -> not equal, and neither is 1 -> broadcasting fails

Error: operands could not be broadcast together with shapes (3,) (2,)

**Practice 2**
You have `prices = np.array([100, 200, 300])` for 3 products and `tax_rates = np.array([0.05, 0.12, 0.18, 0.20])`
for 4 states. Without writing a loop, use broadcasting (via `.reshape`) to build a 3x4 matrix
where `result[i, j]` = price of product `i` with tax rate `j` applied (price * (1 + tax)).

In [11]:
# Your practice code here

## 3. Pandas DataFrame

A DataFrame is a table: rows and columns, like an Excel sheet or SQL table. It's built on top
of NumPy but lets columns have labels and mixed data types.

In [12]:
# Creating a DataFrame from a dictionary
data = {
    "name": ["Amit", "Priya", "Rahul", "Sneha", "Vikram"],
    "age": [25, 30, 22, 28, 35],
    "department": ["Engineering", "Marketing", "Engineering", "HR", "Engineering"],
    "salary": [55000, 62000, 48000, 51000, 71000]
}

df = pd.DataFrame(data)
df

     name  age   department  salary
0    Amit   25  Engineering   55000
1   Priya   30    Marketing   62000
2   Rahul   22  Engineering   48000
3   Sneha   28           HR   51000
4  Vikram   35  Engineering   71000

In [13]:
# Basic inspection methods (use these on EVERY new dataset)
print(df.shape)        # (rows, columns)
print(df.columns.tolist())
print(df.dtypes)
df.info()

(5, 4)
['name', 'age', 'department', 'salary']
name            str
age           int64
department      str
salary        int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   age         5 non-null      int64
 2   department  5 non-null      str
 3   salary      5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [14]:
df.describe()   # quick statistical summary of numeric columns

             age        salary
count   5.000000      5.000000
mean   28.000000  57400.000000
std     4.949747   9235.799911
min    22.000000  48000.000000
25%    25.000000  51000.000000
50%    28.000000  55000.000000
75%    30.000000  62000.000000
max    35.000000  71000.000000

In [15]:
# Selecting columns and rows
print(df["name"])          # single column -> Series
print(df[["name", "age"]]) # multiple columns -> DataFrame

print(df.iloc[0])          # first row by position
print(df.loc[0])           # first row by label (same here since default index)

0      Amit
1     Priya
2     Rahul
3     Sneha
4    Vikram
Name: name, dtype: str
     name  age
0    Amit   25
1   Priya   30
2   Rahul   22
3   Sneha   28
4  Vikram   35
name                 Amit
age                    25
department    Engineering
salary              55000
Name: 0, dtype: object
name                 Amit
age                    25
department    Engineering
salary              55000
Name: 0, dtype: object

**Practice 3**
Create a DataFrame with columns `product`, `price`, `quantity` for 5 fictional products.
Print only the `product` and `price` columns, and print `.describe()` on the whole DataFrame.

In [16]:
# Your practice code here

## 4. Reading CSV / Excel / JSON

In real projects, data almost always comes from a file. Let's first **create** small sample
files (so this notebook is self-contained), then read them back — exactly the same functions
you'd use on real files.

In [17]:
# Create a sample CSV file
df.to_csv("employees.csv", index=False)
print("Saved employees.csv")

# Read it back
csv_df = pd.read_csv("employees.csv")
csv_df

Saved employees.csv

     name  age   department  salary
0    Amit   25  Engineering   55000
1   Priya   30    Marketing   62000
2   Rahul   22  Engineering   48000
3   Sneha   28           HR   51000
4  Vikram   35  Engineering   71000

In [18]:
# Create and read a sample Excel file
# (needs the 'openpyxl' package — install if this errors: pip install openpyxl)
df.to_excel("employees.xlsx", index=False, sheet_name="Sheet1")
print("Saved employees.xlsx")

excel_df = pd.read_excel("employees.xlsx", sheet_name="Sheet1")
excel_df

Saved employees.xlsx

     name  age   department  salary
0    Amit   25  Engineering   55000
1   Priya   30    Marketing   62000
2   Rahul   22  Engineering   48000
3   Sneha   28           HR   51000
4  Vikram   35  Engineering   71000

In [19]:
# Create and read a sample JSON file
df.to_json("employees.json", orient="records", indent=2)
print("Saved employees.json")

json_df = pd.read_json("employees.json")
json_df

Saved employees.json

     name  age   department  salary
0    Amit   25  Engineering   55000
1   Priya   30    Marketing   62000
2   Rahul   22  Engineering   48000
3   Sneha   28           HR   51000
4  Vikram   35  Engineering   71000

**Note:** `pd.read_csv()` has many useful parameters worth knowing:
- `sep=";"` — if the delimiter isn't a comma
- `header=None` — if the file has no header row
- `usecols=["name", "age"]` — load only specific columns
- `dtype={"age": int}` — force column types
- `na_values=["NA", "?"]` — treat these as missing values

**Practice 4**
Save `df` as a CSV called `practice.csv` using a semicolon (`;`) as the separator (hint:
`sep=";"`), then read it back correctly using `pd.read_csv` with the matching `sep`.

In [20]:
# Your practice code here

## 5. Filtering

Filtering means selecting rows that meet some condition — the pandas equivalent of SQL's
`WHERE` clause.

In [21]:
# Boolean mask: a Series of True/False
mask = df["age"] > 25
print(mask)

# Use the mask to filter rows
df[mask]

0    False
1     True
2    False
3     True
4     True
Name: age, dtype: bool

     name  age   department  salary
1   Priya   30    Marketing   62000
3   Sneha   28           HR   51000
4  Vikram   35  Engineering   71000

In [22]:
# You can write it directly, without a separate mask variable
df[df["department"] == "Engineering"]

     name  age   department  salary
0    Amit   25  Engineering   55000
2   Rahul   22  Engineering   48000
4  Vikram   35  Engineering   71000

In [23]:
# Combining conditions: use & (and), | (or), ~ (not)
# IMPORTANT: wrap each condition in parentheses!
df[(df["department"] == "Engineering") & (df["salary"] > 50000)]

     name  age   department  salary
0    Amit   25  Engineering   55000
4  Vikram   35  Engineering   71000

In [24]:
# .query() is often more readable for complex conditions
df.query("age > 25 and department == 'Engineering'")

     name  age   department  salary
4  Vikram   35  Engineering   71000

**Practice 5**
Filter `df` for employees who are NOT in Engineering, sorted by salary descending
(hint: `.sort_values("salary", ascending=False)`).

In [25]:
# Your practice code here

## 6. GroupBy

`groupby` splits the data into groups based on a column, applies an aggregation (sum, mean,
count...) to each group, and combines the results. This is the pandas equivalent of SQL's
`GROUP BY`.

In [26]:
# Average salary per department
df.groupby("department")["salary"].mean()

department
Engineering    58000.0
HR             51000.0
Marketing      62000.0
Name: salary, dtype: float64

In [27]:
# Multiple aggregations at once
df.groupby("department").agg(
    avg_salary=("salary", "mean"),
    total_salary=("salary", "sum"),
    headcount=("name", "count")
)

             avg_salary  total_salary  headcount
department
Engineering     58000.0        174000          3
HR              51000.0         51000          1
Marketing       62000.0         62000          1

In [28]:
# groupby + sort to find the highest-paying department
dept_avg = df.groupby("department")["salary"].mean().sort_values(ascending=False)
dept_avg

department
Marketing      62000.0
Engineering    58000.0
HR             51000.0
Name: salary, dtype: float64

**Practice 6**
Using `df`, group by `department` and find the **max** age in each department. Then find
which department has the youngest maximum age.

In [29]:
# Your practice code here

## 7. Missing Value Handling

Real-world data almost always has gaps. Pandas represents missing values as `NaN`
(Not a Number). Handling them correctly is a critical preprocessing step.

In [30]:
# Create a DataFrame with some missing values
messy = pd.DataFrame({
    "name": ["Amit", "Priya", "Rahul", "Sneha", "Vikram"],
    "age": [25, np.nan, 22, 28, np.nan],
    "salary": [55000, 62000, np.nan, 51000, 71000]
})
messy

     name   age   salary
0    Amit  25.0  55000.0
1   Priya   NaN  62000.0
2   Rahul  22.0      NaN
3   Sneha  28.0  51000.0
4  Vikram   NaN  71000.0

In [31]:
# Detecting missing values
print(messy.isna())          # True where value is missing
print(messy.isna().sum())    # count of missing values PER COLUMN
print(messy.isna().sum().sum())  # total missing values in whole DataFrame

    name    age  salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
4  False   True   False
name      0
age       2
salary    1
dtype: int64
3

In [32]:
# Option 1: Drop rows/columns with missing values
print(messy.dropna())                 # drops any row with at least one NaN
print(messy.dropna(subset=["age"]))   # drops rows where 'age' specifically is NaN

    name   age   salary
0   Amit  25.0  55000.0
3  Sneha  28.0  51000.0
    name   age   salary
0   Amit  25.0  55000.0
2  Rahul  22.0      NaN
3  Sneha  28.0  51000.0

In [33]:
# Option 2: Fill missing values
print(messy.fillna(0))                          # fill with a constant
print(messy["age"].fillna(messy["age"].mean()))  # fill with column mean (common for numeric data)
print(messy.ffill())                             # forward-fill: use previous row's value

     name   age   salary
0    Amit  25.0  55000.0
1   Priya   0.0  62000.0
2   Rahul  22.0      0.0
3   Sneha  28.0  51000.0
4  Vikram   0.0  71000.0
0    25.0
1    25.0
2    22.0
3    28.0
4    25.0
Name: age, dtype: float64
     name   age   salary
0    Amit  25.0  55000.0
1   Priya  25.0  62000.0
2   Rahul  22.0  62000.0
3   Sneha  28.0  51000.0
4  Vikram  28.0  71000.0

In [34]:
# A typical real workflow: fill numeric columns with median, categorical with mode
clean = messy.copy()
clean["age"] = clean["age"].fillna(clean["age"].median())
clean["salary"] = clean["salary"].fillna(clean["salary"].median())
clean

     name   age   salary
0    Amit  25.0  55000.0
1   Priya  25.0  62000.0
2   Rahul  22.0  58500.0
3   Sneha  28.0  51000.0
4  Vikram  25.0  71000.0

**Practice 7**
Create a small DataFrame with a missing value in a categorical column (e.g. `city`).
Fill it with the most frequent value using `.mode()[0]`.

In [35]:
# Your practice code here

## 8. Data Preprocessing

Before feeding data into a model or analysis, you usually need to: fix data types, remove
duplicates, handle outliers, and encode categorical columns as numbers.

In [36]:
# Checking and converting data types
sample = pd.DataFrame({
    "id": ["1", "2", "3"],
    "price": ["100.5", "200.0", "150.25"],
    "date": ["2024-01-01", "2024-02-15", "2024-03-10"]
})
print(sample.dtypes)

sample["id"] = sample["id"].astype(int)
sample["price"] = sample["price"].astype(float)
sample["date"] = pd.to_datetime(sample["date"])
print(sample.dtypes)
sample

id       str
price    str
date     str
dtype: object
id                int64
price           float64
date     datetime64[us]
dtype: object

   id   price       date
0   1  100.50 2024-01-01
1   2  200.00 2024-02-15
2   3  150.25 2024-03-10

In [37]:
# Removing duplicate rows
dup_df = pd.DataFrame({"a": [1, 2, 2, 3], "b": ["x", "y", "y", "z"]})
print(dup_df.duplicated())          # True marks duplicate rows
print(dup_df.drop_duplicates())

0    False
1    False
2     True
3    False
dtype: bool
   a  b
0  1  x
1  2  y
3  3  z

In [38]:
# Encoding categorical variables (models need numbers, not text)

# Label encoding: each category -> an integer (good for ordinal data)
df["dept_label"] = df["department"].astype("category").cat.codes
print(df[["department", "dept_label"]])

# One-hot encoding: each category -> its own 0/1 column (better for non-ordinal data)
one_hot = pd.get_dummies(df["department"], prefix="dept")
print(one_hot)

    department  dept_label
0  Engineering           0
1    Marketing           2
2  Engineering           0
3           HR           1
4  Engineering           0
   dept_Engineering  dept_HR  dept_Marketing
0              True    False           False
1             False    False            True
2              True    False           False
3             False     True           False
4              True    False           False

In [39]:
# Scaling numeric features (many ML models need similar ranges across columns)

# Min-Max scaling -> squashes values into [0, 1]
def min_max_scale(col):
    return (col - col.min()) / (col.max() - col.min())

df["salary_scaled"] = min_max_scale(df["salary"])

# Standardization (z-score) -> mean 0, std 1
def z_score(col):
    return (col - col.mean()) / col.std()

df["salary_zscore"] = z_score(df["salary"])
df[["salary", "salary_scaled", "salary_zscore"]]

   salary  salary_scaled  salary_zscore
0   55000       0.304348      -0.259858
1   62000       0.608696       0.498062
2   48000       0.000000      -1.017779
3   51000       0.130435      -0.692956
4   71000       1.000000       1.472531

**Practice 8**
Take the `age` column from `df`, apply min-max scaling, and store it as a new column
`age_scaled`. Confirm the min is 0 and the max is 1.

In [40]:
# Your practice code here

## 9. Feature Engineering Basics

Feature engineering means creating new, more useful columns from existing data — often the
difference between a mediocre model and a good one.

In [41]:
# 1. Creating a feature from an existing numeric column
df["salary_per_year_of_age"] = df["salary"] / df["age"]
df[["name", "age", "salary", "salary_per_year_of_age"]]

     name  age  salary  salary_per_year_of_age
0    Amit   25   55000             2200.000000
1   Priya   30   62000             2066.666667
2   Rahul   22   48000             2181.818182
3   Sneha   28   51000             1821.428571
4  Vikram   35   71000             2028.571429

In [42]:
# 2. Binning a continuous column into categories
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 30, 100],
    labels=["Young", "Mid", "Senior"]
)
df[["name", "age", "age_group"]]

     name  age age_group
0    Amit   25     Young
1   Priya   30       Mid
2   Rahul   22     Young
3   Sneha   28       Mid
4  Vikram   35    Senior

In [43]:
# 3. Extracting features from dates (very common in real projects)
dates = pd.DataFrame({"joined": pd.to_datetime(["2022-01-15", "2023-06-30", "2021-11-05"])})
dates["join_year"] = dates["joined"].dt.year
dates["join_month"] = dates["joined"].dt.month
dates["join_dayofweek"] = dates["joined"].dt.day_name()
dates

      joined  join_year  join_month join_dayofweek
0 2022-01-15       2022           1       Saturday
1 2023-06-30       2023           6         Friday
2 2021-11-05       2021          11         Friday

In [44]:
# 4. Combining columns into a new feature (text example)
df["name_department"] = df["name"] + " (" + df["department"] + ")"
df[["name_department"]]

        name_department
0    Amit (Engineering)
1     Priya (Marketing)
2   Rahul (Engineering)
3            Sneha (HR)
4  Vikram (Engineering)

**Practice 9 (mini end-to-end task)**
Using the `employees.csv` file you saved earlier:
1. Read it into a fresh DataFrame.
2. Add a column `is_senior` that is `True` if age > 28, else `False`.
3. Group by `department` and find the average salary of only the senior employees
   (hint: filter first, then groupby).

In [45]:
# Your practice code here

## Summary

You've now covered the core NumPy + Pandas toolkit used in almost every data analysis
project: creating and manipulating arrays, broadcasting, building and inspecting DataFrames,
reading real files, filtering, grouping, handling missing data, and basic preprocessing /
feature engineering.

**Next notebook:** `02_data_visualization_sql.ipynb` — plotting with Matplotlib and querying
data with SQL.